version: '2'
services:
  customers-db:
    image: postgres:9.5.3
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=customers
      - POSTGRES_DB=customers_development
    volumes_from:
      - customers-data
  customers-data:
    image: postgres:9.5.3
    volumes:
      - /var/lib/postgresql
    command: "true"
  customers-migrate:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - customers-db
    environment:
      - PASSENGER_APP_ENV=development
    command: ["./wait-for-postgres.sh", "customers-db", "bin/rails", "db:migrate"]
  customers:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - customers-db
      - customers-migrate
    ports:
      - "80:80"
    environment:
      - PASSENGER_APP_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - .:/home/app/webapp
